#!/usr/bin/env ruby

require "twitter"

GRAPHICS_MAGICK_PATH = "/usr/local/bin/gm"
FFMPEG_PATH = "/usr/local/bin/ffmpeg"

client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "YOUR_CONSUMER_KEY"
  config.consumer_secret     = "YOUR_CONSUMER_SECRET"
  config.access_token        = "YOUR_ACCESS_TOKEN"
  config.access_token_secret = "YOUR_ACCESS_SECRET"
end

# Copy original mp4 to ~/.twizo/#{Time.now.to_i}
working_dir = File.expand_path("~/.twizo/#{Time.now.to_i}/")
org_movie_path = ARGV[0].gsub(/^file:\/\//, "")
new_movie_path = File.join(working_dir, "movie.mp4")
system("mkdir -p #{working_dir}")
system("cp #{org_movie_path} #{new_movie_path}")

# Convert ~/.twizo/#{Time.now.to_i}/movie.mp4 to ~/.twizo/#{Time.now.to_i}/movie.gif
mp4_path = new_movie_path
gif_path = File.join(working_dir, "movie.gif")
system("#{FFMPEG_PATH} -i #{mp4_path} -r 10 #{File.join(working_dir, '%04d.png')} >& /dev/null")
system("#{GRAPHICS_MAGICK_PATH} convert -delay 10 #{File.join(working_dir, '*.png')} #{gif_path} >& /dev/null")

# Tweet empty string gif url
client.update_with_media("", File.open(gif_path))
